name: Quick Gate
description: Run deterministic quality gates on a Next.js project and optionally auto-repair lint/type failures.
author: Hermes Labs

inputs:
  mode:
    description: Gate mode -- "canary" (lint + typecheck + lighthouse) or "full" (adds build)
    required: false
    default: canary
  repair:
    description: Run bounded repair after gate failures (deterministic-only in CI, no Ollama required)
    required: false
    default: "true"
  max-attempts:
    description: Maximum repair attempts before escalation
    required: false
    default: "2"
  node-version:
    description: Node.js version to use
    required: false
    default: "20"
  post-comment:
    description: Post findings as a PR comment (requires pull_request trigger)
    required: false
    default: "true"

outputs:
  status:
    description: Overall gate result -- "pass", "fail", or "escalated"
    value: ${{ steps.gate.outputs.status }}
  failures-json:
    description: Path to .quick-gate/failures.json (empty if pass)
    value: ${{ steps.gate.outputs.failures_json }}
  repair-status:
    description: Repair result -- "pass", "escalated", or "skipped"
    value: ${{ steps.repair.outputs.status }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Detect changed files
      id: changed
      shell: bash
      run: |
        CHANGED_FILE=$(mktemp)
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.sha }} > "$CHANGED_FILE"
        else
          git diff --name-only HEAD~1 > "$CHANGED_FILE" 2>/dev/null || echo "" > "$CHANGED_FILE"
        fi
        echo "changed_file=$CHANGED_FILE" >> "$GITHUB_OUTPUT"
        echo "Changed files:"
        cat "$CHANGED_FILE"

    - name: Install Quick Gate
      shell: bash
      run: npm install -g quick-gate@latest

    - name: Run quality gates
      id: gate
      shell: bash
      run: |
        set +e
        quick-gate run --mode ${{ inputs.mode }} --changed-files "${{ steps.changed.outputs.changed_file }}"
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -eq 0 ]; then
          echo "status=pass" >> "$GITHUB_OUTPUT"
          echo "failures_json=" >> "$GITHUB_OUTPUT"
        else
          echo "status=fail" >> "$GITHUB_OUTPUT"
          echo "failures_json=.quick-gate/failures.json" >> "$GITHUB_OUTPUT"
        fi

    - name: Run bounded repair
      id: repair
      if: steps.gate.outputs.status == 'fail' && inputs.repair == 'true'
      shell: bash
      run: |
        set +e
        quick-gate repair \
          --input .quick-gate/failures.json \
          --max-attempts ${{ inputs.max-attempts }} \
          --deterministic-only
        EXIT_CODE=$?
        set -e

        if [ $EXIT_CODE -eq 0 ]; then
          echo "status=pass" >> "$GITHUB_OUTPUT"
        else
          echo "status=escalated" >> "$GITHUB_OUTPUT"
        fi

    - name: Skip repair
      id: repair-skip
      if: steps.gate.outputs.status == 'pass' || inputs.repair != 'true'
      shell: bash
      run: echo "status=skipped" >> "$GITHUB_OUTPUT"

    - name: Post PR comment
      if: >-
        github.event_name == 'pull_request' &&
        inputs.post-comment == 'true' &&
        steps.gate.outputs.status == 'fail'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        REPAIR_STATUS="${{ steps.repair.outputs.status || steps.repair-skip.outputs.status }}"

        # Build comment body
        BODY="## Quick Gate Report"
        BODY="$BODY"$'\n\n'"**Gate status:** ${{ steps.gate.outputs.status }}"
        BODY="$BODY"$'\n'"**Repair status:** $REPAIR_STATUS"

        if [ -f ".quick-gate/failures.json" ]; then
          FINDING_COUNT=$(node -e "const f=JSON.parse(require('fs').readFileSync('.quick-gate/failures.json','utf8')); console.log(f.findings?.length || 0)")
          BODY="$BODY"$'\n'"**Findings:** $FINDING_COUNT"
          BODY="$BODY"$'\n\n'"<details><summary>Failure details</summary>"$'\n\n'"\`\`\`json"
          BODY="$BODY"$'\n'"$(node -e "const f=JSON.parse(require('fs').readFileSync('.quick-gate/failures.json','utf8')); console.log(JSON.stringify(f.findings,null,2))")"
          BODY="$BODY"$'\n'"\`\`\`"$'\n\n'"</details>"
        fi

        if [ -f ".quick-gate/escalation.json" ]; then
          REASON=$(node -e "const e=JSON.parse(require('fs').readFileSync('.quick-gate/escalation.json','utf8')); console.log(e.reason_code || 'UNKNOWN')")
          BODY="$BODY"$'\n\n'"**Escalation reason:** \`$REASON\`"
        fi

        BODY="$BODY"$'\n\n'"---"$'\n'"*Generated by [Quick Gate](https://github.com/roli-lpci/quick-gate-js)*"

        gh pr comment ${{ github.event.pull_request.number }} --body "$BODY"

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: quick-gate-report
        path: .quick-gate/
        if-no-files-found: ignore
